---
- name: create ec2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: launch ec2
      ec2:
        key_name: keys
        instance_type: t2.micro
        region: us-east-1
        image: ami-09a5b0b7edf08843d
        wait: yes
        group: default
        count: 1
        vpc_subnet_id: subnet-21fb572f
        assign_public_ip: yes
      register: ec2_out

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: uml
      with_items: "{{ ec2_out.instances }}"

    - name: wait for ssh to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2_out.instances }}"

- name: configure instances
  hosts: uml
  become: true
  gather_facts: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
      become: yes

    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: install php
      yum:
        name: php
        state: present

    - name: create file
      copy:
        dest: "/var/www/html/file.php"
        content: "<?php echo "This is my PHP"; ?>"

    - name: restart httpd
      service:
      name: httpd
      state: restarted
