---
- name: create ec2
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: launch ec2
      ec2:
        key_name: keys
        instance_type: t2.micro
        region: us-east-1
        image: ami-09a5b0b7edf08843d
        wait: yes
        group: default
        count: 2
        vpc_subnet_id: subnet-21fb572f
        assign_public_ip: yes
      register: ec2_out

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: uml
      with_items: "{{ ec2_out.instances }}"

    - name: wait for ssh to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2_out.instances }}"

- name: configure instances
  hosts: uml
  become: true
  gather_facts: true
  tasks:
    - name: Installing docker
      yum:
        name: docker
        state: present
      become: yes

    - name: Ensuring service started
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: pull postgres image
      command: docker pull postgres

    - name: start postgres container
      command: docker run --name postgres_db -e POSTGRES_PASSWORD=password -d postgres

